version: "3"
networks:
  app-network:
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inetumdb
      - MYSQL_ROOT_USER=root
#      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - app-network
  spring-container:
    image: spring-container
    restart: unless-stopped
    ports:
     - "8280:8280"
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/inetumdb?allowPublicKeyRetrieval=true&useSSL=false
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=root
     - ALFRESCO_REPOSITORY_URL=http://172.28.0.1:8087/alfresco
     - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
    build:
     context: "./"
    depends_on:
      - mysqldb
    networks:
      - app-network